rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  comma-dangle:
    - 2
    - always-multiline
  keyword-spacing:
    - 2
    -
      before: true
      after: true
  space-before-blocks:
    - 2
    - always
  eol-last:
    - 2
    - always
ecmaFeatures:
  modules:
    true
env:
  es6: true
  node: true
extends: 'eslint:recommended'
